"""Stage 04 - Render MD: the second representation of the same content.

Contract: ../CONTEXT.md

Markdown is a WRAPPER here, not an editorial pass: `activity` goes in whole,
unshortened, unformatted. The anchor at each entry is the target of `raw_ref`
from the index - without it, the index would point at an empty place.

The filename comes from doc_key, not from the source filename: recurring
reports frequently reuse identical filenames across periods.
"""

import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

STAGE_DIR = Path(__file__).resolve().parents[1]
FLOW_ROOT = STAGE_DIR.parents[1]
PROJECT_ROOT = FLOW_ROOT.parents[1]

VALIDATED = STAGE_DIR.parent / "03_validate" / "output" / "validated.json"
KB_MD_DIR = PROJECT_ROOT / "_kb" / "md"

SECTION_ORDER = ["finance", "business_unit", "product", "event", "case_study"]
SECTION_TITLES = {
    "finance": "1. Financial Index",
    "business_unit": "2. Business Unit Support",
    "product": "3. Product Management",
    "event": "4. Events",
    "case_study": "5. Case Studies",
}


def render(data):
    doc_key = data["doc_key"]
    entries = data["entries"]
    out = [
        f"# {doc_key} — Weekly Report",
        "",
        "| | |",
        "|---|---|",
        f"| Document key | `{doc_key}` |",
        f"| Report date | {entries[0]['report_date'] if entries else '—'} |",
        f"| Source file | `{data['entries'][0]['source_file'] if entries else '—'}` |",
        f"| Entries | {len(entries)} |",
        "",
        "> Generated by `build_kb/04_render_md`. The `activity` text is copied",
        "> from the source 1:1 — do not edit it here. Corrections belong in the",
        "> source or in the stage contract, never in this generated file.",
        "",
    ]

    for section in SECTION_ORDER:
        rows = [e for e in entries if e["section"] == section]
        out.append(f"## {SECTION_TITLES[section]}")
        out.append("")
        if not rows:
            # An empty section is stated, not skipped - otherwise there is no
            # way to tell "nothing happened" from "extraction missed something".
            out += ["*(no entries in this report)*", ""]
            continue
        for e in rows:
            out.append(f'<a id="{e["entry_id"]}"></a>')
            out.append(f'### {e["object_name"]} · `{e["entry_id"]}`')
            out.append("")
            meta = [f"**PIC:** {', '.join(e['pic']) if e['pic'] else '—'}",
                    f"**Client:** {e['client']}", f"**Opportunity:** {e['bo']}"]
            out.append(" · ".join(meta))
            out.append("")
            out.append(e["activity"])
            out += ["", f"<sub>`activity_sha256: {e['activity_sha256'][:16]}…`</sub>", ""]

    if data.get("issues"):
        out += ["---", "", "## To review", ""]
        out += [f"- {i}" for i in data["issues"]] + [""]

    out += ["---", "", f"**Generated:** {datetime.now(timezone.utc).date()}"]
    return "\n".join(out)


def main():
    if not VALIDATED.is_file():
        print("ERROR: validated.json not found - run Stage 03 first.", file=sys.stderr)
        return 1

    data = json.loads(VALIDATED.read_text(encoding="utf-8"))
    entries = data["entries"]
    text = render(data)

    # Gate: anchor count must match entry count, or raw_ref from the index
    # would point somewhere that doesn't exist.
    anchors = sum(1 for e in entries if f'id="{e["entry_id"]}"' in text)
    if anchors != len(entries):
        print(f"ERROR: {anchors} anchors for {len(entries)} entries - run stopped.", file=sys.stderr)
        return 1

    # Gate: content must land in the file unchanged.
    for e in entries:
        if e["activity"] not in text:
            print(f"ERROR: entry {e['entry_id']}'s content did not make it into the Markdown verbatim.", file=sys.stderr)
            return 1
        if hashlib.sha256(e["activity"].encode("utf-8")).hexdigest() != e["activity_sha256"]:
            print(f"ERROR: entry {e['entry_id']}'s hash does not match its content.", file=sys.stderr)
            return 1

    KB_MD_DIR.mkdir(parents=True, exist_ok=True)
    target = KB_MD_DIR / f"{data['doc_key']}.md"
    target.write_text(text, encoding="utf-8")

    print(f"OK  {data['doc_key']}  entries: {len(entries)}  anchors: {anchors}")
    print(f"    {target.relative_to(PROJECT_ROOT)}  ({len(text)} characters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
